### ISSUE TITLE
please

### ISSUE THREAD

**Issue by SunkerMacgunker** [ZedDevStuff/USTManager#14]
After updating to the new version, replacements for the LandingHeavy sound, the enrage sound, and the gab2nd_introb sound do not play and are instead the normal versions that are in base game

**Comment by ZedDevStuff** [comment]
They probably worked due to the experimental feature I forgot to disable.
Sadly it made the mod basically unusable if you wanted to changes USTs in
game. I'm working on making it work and when it's done, every sound that
doesn't work right now should just work

Le sam. 27 janv. 2024, 00:27, SunkerMacgunker ***@***.***> a
écrit :

**Comment by SunkerMacgunker** [comment]
Thank you for the response, I await this update
PS: the mod itself is Very well done, I appreciate it much

**Comment by SunkerMacgunker** [comment]
I Must ask, is there any way to downgrade to the previous version of the mod in the meantime while whatever bugs are being ironed out?

**Comment by ZedDevStuff** [comment]
Sure, if you're using r2modman, uninstall the mod and redownload it. There
should be a dropdown to select the version before confirming the download.
On Thunderstore, you can just open the versions tab on the mod page and
download the mod manually

Le dim. 28 janv. 2024, 18:14, SunkerMacgunker ***@***.***> a
écrit :

**Comment by SunkerMacgunker** [comment]
This has worked perfectly, thank you

**Comment by ZedDevStuff** [comment]
> This has worked perfectly, thank you

The new update (1.4.3) should work. Please give it a try
