### ISSUE TITLE
Struggles

### ISSUE THREAD

**Issue by pogdogpy** [ZedDevStuff/USTManager#2]
i am really struggling figuring out how this works, maybe it could have some preset ones for boss levels and/or normal levels, since i and probably some other people tend to find it easier to see how its done then copy it, or a video tutorial maybe, that, in my opinion would make it alot easier :D

**Comment by ZedDevStuff** [comment]
If you open your game folder and go to the USTs folder, there should be a template that gets regenerated each time you launch the game. Use that. There are further instructions in it and make sure the .ust file in your pack isn't called template, otherwise it won't load

**Comment by pogdogpy** [comment]
should i be removing all of the level sections im not using, i got super confused about clip sounds and if the global bit at the top should have the song/sound you want or the song/sound your replacing, if you dont mind could you go into further detail?

**Comment by ZedDevStuff** [comment]
Ideally, yes. Remove any unused entry. You can also read the readme.md file
in the template folder. It should give a few instructions. As for global,
it's for anything you want that isn't covered by the regular system (non
music sounds basically). You technically can use global for music but it's
less convenient because you need to know the name of the audio clips

**Comment by ZedDevStuff** [comment]
Also I'm about to sleep so further questions won't be answered for a few hours

**Comment by pogdogpy** [comment]
alright thank you, ill give it a shot
