### ISSUE TITLE
Some Struggles

### ISSUE THREAD

**Issue by Abel-sketch** [ZedDevStuff/USTManager#4]
I have read the read me text, yet I still don´t know how to add a song :‹

**Comment by ZedDevStuff** [comment]
Its pretty simple. If you already have a song pack, just drop it in the USTs folder in the ULTRAKILL folder, otherwise copy the template and replace the parts you want in template.ust . Here is a working one if you want to look at. It replaces the song in 0-1

[Example.zip](https://github.com/ZedDevStuff/USTManager/files/13841345/Example.zip)

Your .ust file should never be called template.ust, otherwise USTManager will ignore it. Also you don't need an icon but you can add one anyway, just make sure it's called icon.png
